// Generated by CoffeeScript 1.9.0
var fs;

fs = require('fs');

module.exports = function() {
  var file;
  if (!fs.existsSync("./archives")) {
    fs.mkdirSync("./archives");
  }
  if (!fs.existsSync("./archives/sites.txt")) {
    file = fs.openSync("./archives/sites.txt", "w");
    fs.closeSync(file);
  }
  if (!fs.existsSync("./archives/sites")) {
    return fs.mkdirSync("./archives/sites");
  }
};
