// Generated by CoffeeScript 1.9.0
var archive, httpHelper, pathLib, urlLib;

pathLib = require('path');

archive = require('../helpers/archive-helpers.js');

urlLib = require('url');

httpHelper = require('./http-helpers.js');

exports.handleRequest = function(req, res) {
  var data, parts, pathname, url;
  if (req.method === "GET") {
    url = req.url;
    parts = urlLib.parse(url);
    pathname = parts.pathname;
    if (pathname === '/') {
      pathname = pathLib.join(pathname, 'index.html');
    }
    httpHelper.serveAssets(res, pathname);
  }
  if (req.method === "POST") {
    data = "";
    req.on('data', function(bin) {
      return data += bin;
    });
    return req.on('end', function(url) {
      return archive.isUrlInList(url, function(inTheList) {
        if (inTheList) {
          return archive.isUrlInArchive(url, function(inTheArchive) {
            if (inTheArchive) {
              return httpHelper.sendRedirect(res, url);
            } else {
              httpHelper.sendRedirect(res, '/loading.html');

              /* 
              TODO: Fetch and add to archive.
               */
              return archive.downloadUrls(url);
            }
          });
        } else {
          archive.addUrlToList(url, function() {
            return httpHelper.sendRedirect(res, '/loading.html');
          });
          return archive.downloadUrls(url);
        }
      });
    });
  }
};


/*
//////////////////////////////////////////////////////
/////////////////  QQQQQQQQQQQQQQQQ //////////////////
//////////////////////////////////////////////////////
// When client first connects to the server it sends GET? what does it ask for in the GET? i.e. data part.
 */
